### ISSUE TITLE
Board Image

### ISSUE THREAD

**Issue by huhuhaxa** [akicho8/shogi-player#40]
@akicho8 Is there any png file for just the grey board used on the README section?

**Comment by akicho8** [comment]
@huhuhaxa Sorry for not noticing the comments.

There is no gray PNG on shogi board, but it will be better to capture the screen from here.
https://www.shogi-extend.com/share-board?body=position.sfen.9%2F9%2F9%2F9%2F9%2F9%2F9%2F9%2F9.b.-.1&turn=0&abstract_viewpoint=black

You can customize various colors here (Sorry for Japanese)
https://akicho8.github.io/shogi-player/editor
